tags:
  - name: booking-service
    description: booking-service API

paths:
  /api/v1.0/bookings:
    # [POST] Create a booking
    post:
      tags:
        - booking-service
      summary: Create a booking
      description: Create a booking
      operationId: createBooking
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Booking object that needs to be added
          required: true
          schema:
            $ref: "#/definitions/Booking"
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/BookingAddResponse"
        400:
          description: Invalid input
        409:
          description: Booking already exists
        500:
          description: Internal server error

# definitions
definitions:
  Booking:
    type: object
    properties:
      email:
        type: string
        description: Email of the principal guest
      firstName:
        type: string
        description: First name of the principal guest
      lastName:
        type: string
        description: Last name of the principal guest
      checkIn:
        type: string
        description: Check In Date
      checkOut:
        type: string
        description: Check Out Date
      totalGuests:
        type: number
        description:  Total number of guests
      roomType:
        type: string
        description:  Room type - 'presidential suite'

  BookingAddResponse:
    type: object
    properties:
      id:
        type: string
        description: Booking ID
      detailsLink:
        type: string
        description: Link to booking details
      cancelLink:
        type: string
        description: Link to cancel booking


schemes:
  - https
  - http
