# baseURL
@baseURL = http://localhost:3000/api/v1.0

###
# Create Booking
POST {{ baseURL }}/bookings
Content-Type: application/json

{
  "email": "a@a.com",
  "firstName": "John",
  "lastName": "Doe",
  "checkIn": "2023-01-21",
  "checkOut": "2023-01-23",
  "totalGuests":3,
	"roomType": "presidential suite"
}


###
# View Booking
GET {{ baseURL }}/bookings/164447b6-0a66-47f2-a44d-33e6f504843a
Content-Type: application/json

###
# Cancel Booking
GET {{ baseURL }}/bookings/559f0ba1-154a-4f60-ba25-0beeb97167e2/cancel
Content-Type: application/json
